### ISSUE TITLE
4-clause BSD license is incompatible with the GNU GPL.

### ISSUE THREAD

**Issue by kubo** [gdabah/distorm#104]
Could you change the license from 4-clause BSD license to 2 or 3-clause BSD license?
The 4-clause BSD license is incompatible with the GNU GPL.
See: https://www.gnu.org/licenses/license-list.html#OriginalBSD
It cannot be combined with GPL'ed software.

**Comment by gdabah** [comment]
Thanks, will check it out.

**Comment by gdabah** [comment]
Done, thanks.
