### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_distorm_decode64" macOS

### ISSUE THREAD

**Issue by karek314** [gdabah/distorm#107]
Hi, getting problem with distorm_decode and project [libembryo](https://github.com/karek314/libembryo/blob/master/src/mem/memmgr.cpp#L77)

Project on repository is not compatible with x86_64, i have made few improvements to x86_64 also updated distorm to latest version and compiled with default settings to support x64 but still getting this issue. Im pretty sure its related to distorm.

```
Undefined symbols for architecture x86_64:
  "_distorm_decode64", referenced from:
      embryo::memmgr::disasm(void*, unsigned int, unsigned int) in libembryo.a(memmgr.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by gdabah** [comment]
How come you have the prefix '_' before distorm_decode64? What arch do you compile for?
See wiki: https://github.com/gdabah/distorm/wiki/BuildCompilationEnvironment#the-offset-type-case

**Comment by karek314** [comment]
There is no prefix - https://github.com/karek314/libembryo/blob/master/src/mem/memmgr.cpp#L77
Compiling for x86_64
