### ISSUE TITLE
Please, provide a SONAME

### ISSUE THREAD

**Issue by eribertomota** [gdabah/distorm#109]
Hi,

The SONAME[1] is need to provide a version information of the library. From Program-Library-HOWTO[2]:

"Every shared library has a special name called the soname. [...] Every shared library also has a real name, which is the filename containing the actual library code."

I am generating a SONAME for distorm3 in Debian via LDFLAGS[3].

Can you modify the lib to have a built-in SONAME?

[1] https://en.wikipedia.org/wiki/Soname
[2] http://www.tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html#AEN49
[3] https://sources.debian.net/src/distorm3/3.3.4-2/debian/rules/

Thanks a lot in advance.

Regards,

Eriberto

**Comment by gdabah** [comment]
Hi

Can you submit a pull request or send a patch my way?
Thanks

**Comment by gdabah** [comment]
Is that the rules file attached in #3?

**Comment by eribertomota** [comment]
Hi,

Thanks for your reply.

2016-12-19 11:43 GMT-02:00 Gil Dabah <notifications@github.com>:

> Is that the rules file attached in #3
> <https://github.com/gdabah/distorm/issues/3>?
>


I think that no. However, I can't help more or send a patch because I am
not a programmer. Sorry. However, all libraries have SONAME. So, i think
that you can follow an example.

Cheers,

Eriberto

**Comment by gdabah** [comment]
Hi @eribertomota 
I added something, not sure if it really solves the problem.
You're welcome to take a look at the make file [here](https://github.com/gdabah/distorm/blob/master/make/linux/Makefile).

**Comment by gdabah** [comment]
@eribertomota Hey, I added the soname to the gcc command line in the makefile. So I'm surprised it doesn't work. However, in the file you sent a link to, I see it's different command than last time...

**Comment by gdabah** [comment]
@eribertomota BTW - how do you compile the project?

**Comment by eribertomota** [comment]
Hi,

If you use Debian, you can do:

# apt-get install debhelper devscripts
$ apt-get source distorm3
$ cd distorm3-<version>
$ debuild

If you want try it over Debian Sid (we almost always do uploads to Sid, aka unstable), you can do inside Debian Stable, Ubuntu, Mint, etc):

# mkdir /sid-jail
# debootstrap sid /sid-jail http://ftp.debian.org/debian
# chroot /sid-jail
# echo proc /proc proc defaults 0 0 >> /etc/fstab
# mount /proc

 and...

# apt-get install debhelper devscripts
$ apt-get source distorm3
$ cd distorm3-<version>
$ debuild

You also can see the build log clicking over any 'installed' here[1].

[1] https://buildd.debian.org/status/package.php?p=distorm3&suite=sid

Cheers,

Eriberto

**Comment by eribertomota** [comment]
From: Gil Dabah
Date: Sat, Nov 10, 2018 at 8:29 PM

Hi Eriberto
Thanks for your kind help!

Perhaps you can try compiling from the terminal with running the make file under the /make/linux and then see if the SONAME exists.

-----

Hi Gil, you are right. The SONAME exists now. I will fix the Debian package.

Thanks a lot for your nice work.

Cheers,

Eriberto

**Comment by eribertomota** [comment]
Hi Gil,

I am reopening this bug. 

Building via setup.py produces a library without SONAME. See:

# cd make/linux/
# make
# objdump -x libdistorm3.so | grep SONAME
  SONAME               libdistorm3.so.3
# 


# python setup.py build
# objdump -x build/lib.linux-x86_64-2.7/distorm3/libdistorm3.so | grep SONAME
# 

Cheers,

Eriberto

**Comment by gdabah** [comment]
@eribertomota 
Weird, I added it to setup.py already. Can you please attach the compilation log from setup.py?

**Comment by eribertomota** [comment]
Please, see below:

```
# python setup.py build
running build
running custom_build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/distorm3
copying python/distorm3/__init__.py -> build/lib.linux-x86_64-2.7/distorm3
running build_clib
running custom_build_clib
building 'distorm3' library
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-A8UpPM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -Iinclude -c src/decoder.c -o build/temp.linux-x86_64-2.7/src/decoder.o -fPIC -O2 -Wall -DSUPPORT_64BIT_OFFSET -DDISTORM_STATIC -Wl,-soname,libdistorm3.so.3
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-A8UpPM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -Iinclude -c src/distorm.c -o build/temp.linux-x86_64-2.7/src/distorm.o -fPIC -O2 -Wall -DSUPPORT_64BIT_OFFSET -DDISTORM_STATIC -Wl,-soname,libdistorm3.so.3
src/distorm.c:410:26: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 _DLLEXPORT_ unsigned int distorm_version()
                          ^~~~~~~~~~~~~~~
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-A8UpPM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -Iinclude -c src/instructions.c -o build/temp.linux-x86_64-2.7/src/instructions.o -fPIC -O2 -Wall -DSUPPORT_64BIT_OFFSET -DDISTORM_STATIC -Wl,-soname,libdistorm3.so.3
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-A8UpPM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -Iinclude -c src/insts.c -o build/temp.linux-x86_64-2.7/src/insts.o -fPIC -O2 -Wall -DSUPPORT_64BIT_OFFSET -DDISTORM_STATIC -Wl,-soname,libdistorm3.so.3
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-A8UpPM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -Iinclude -c src/mnemonics.c -o build/temp.linux-x86_64-2.7/src/mnemonics.o -fPIC -O2 -Wall -DSUPPORT_64BIT_OFFSET -DDISTORM_STATIC -Wl,-soname,libdistorm3.so.3
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-A8UpPM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -Iinclude -c src/operands.c -o build/temp.linux-x86_64-2.7/src/operands.o -fPIC -O2 -Wall -DSUPPORT_64BIT_OFFSET -DDISTORM_STATIC -Wl,-soname,libdistorm3.so.3
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-A8UpPM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -Iinclude -c src/prefix.c -o build/temp.linux-x86_64-2.7/src/prefix.o -fPIC -O2 -Wall -DSUPPORT_64BIT_OFFSET -DDISTORM_STATIC -Wl,-soname,libdistorm3.so.3
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-A8UpPM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -Iinclude -c src/textdefs.c -o build/temp.linux-x86_64-2.7/src/textdefs.o -fPIC -O2 -Wall -DSUPPORT_64BIT_OFFSET -DDISTORM_STATIC -Wl,-soname,libdistorm3.so.3
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-A8UpPM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -Iinclude -c src/wstring.c -o build/temp.linux-x86_64-2.7/src/wstring.o -fPIC -O2 -Wall -DSUPPORT_64BIT_OFFSET -DDISTORM_STATIC -Wl,-soname,libdistorm3.so.3
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-A8UpPM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-A8UpPM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/decoder.o build/temp.linux-x86_64-2.7/src/distorm.o build/temp.linux-x86_64-2.7/src/instructions.o build/temp.linux-x86_64-2.7/src/insts.o build/temp.linux-x86_64-2.7/src/mnemonics.o build/temp.linux-x86_64-2.7/src/operands.o build/temp.linux-x86_64-2.7/src/prefix.o build/temp.linux-x86_64-2.7/src/textdefs.o build/temp.linux-x86_64-2.7/src/wstring.o -o build/lib.linux-x86_64-2.7/distorm3/libdistorm3.so

```

**Comment by gdabah** [comment]
I fixed the side warning..
But I see the soname param at the end of the line. So something's weird.

**Comment by eribertomota** [comment]
Em qui, 22 de nov de 2018 às 07:06, Gil Dabah <notifications@github.com>
escreveu:

> I fixed the side warning..
> But I see the soname param at the end of the line. So something's weird.
>
>
>
Do you are using Windows? If yes, can you install a Linux in a virtual
machine? I think that I can help you to trace the problem.

**Comment by gdabah** [comment]
@eribertomota I made some fix, can you retry please? Confirmed on a linux box.

**Comment by eribertomota** [comment]
```
# objdump -x build/lib.linux-x86_64-2.7/distorm3/libdistorm3.so | grep -i soname
  SONAME               libdistorm3.so.3

# objdump -x debian/tmp/usr/lib/python2.7/dist-packages/distorm3/libdistorm3.so | grep -i soname
  SONAME               libdistorm3.so.3
```

Solved! Thanks!

Now I suggest you publish the library using real name (libdistorm3.so.3.3.8, instead of libdistorm3.so). You can use a symlink to point libdistorm3.so to already created libdistorm3.so.3.3.8. Rationale: you are the upstream and you know lib version is 3.3.8. As user, I can deduce that libdistorm3.so and libdistorm3.so.3 are generated  by libdistorm3.so.3.3.8. However, I never can deduce that 3.3.8 version exists seeing libdistorm3.so only. The most of libs publishes the real name and, several times, other relative names via symlink.

Thanks again!

Eriberto

**Comment by gdabah** [comment]
@eribertomota Hi man, I updated makefile to reflect what you requested. Can you give it a shoot again please? :)

**Comment by eribertomota** [comment]
Hi Gil,

Fine in make/linux/, but it should be the result produced by setup.py too. This is the way adopted by 99% of libraries.

Thanks!

**Comment by gdabah** [comment]
@eribertomota do you know a library that does this too if it's done by 99% of them ? :)

**Comment by gdabah** [comment]
@eribertomota unless the Extension class of distutils should do it automatically?

**Comment by eribertomota** [comment]
Em qua, 12 de dez de 2018 às 17:18, Gil Dabah <notifications@github.com>
escreveu:

> @eribertomota <https://github.com/eribertomota> unless the Extension
> class of distutils should do it automatically?
>
>
> Hi Gil,

I maintain some libraries in Debian but only distorm3 is created by a
setup.py. I think that is it you want. I have a tip.

1. Go to https://codesearch.debian.net
2. Put 'soname' in Search field.
3. After the search, set 'Group search results by Debian source package'.
4. Alternatively, you can search for 'setup.py'.

Is it what you need?

Cheers,

Eriberto

**Comment by gdabah** [comment]
Hey @eribertomota 
I added it to setup.py already back then, still nothing?
Arrg, it's been a year now, sorry. :(

**Comment by eribertomota** [comment]
Sorry for my long delay. Working now, thanks.
