### ISSUE TITLE
many warnings reported by clang

### ISSUE THREAD

**Issue by swigger** [gdabah/distorm#115]
../../../share/xdetour/distorm/insts.c:1764:19: warning: suggest braces around initialization of subobject [-Wmissing-braces]
            /*II_0F_AE_00*/{ 0x170, 9886, 0x0, 0, 0, 0, 9894 },
                             ^~~~~~~~~~~
                             {          }
    ../../../share/xdetour/distorm/insts.c:1765:19: warning: suggest braces around initialization of subobject [-Wmissing-braces]
            /*II_0F_AE_01*/{ 0x170, 9914, 0x0, 0, 0, 0, 9923 },
                             ^~~~~~~~~~~
                             {          }
    ../../../share/xdetour/distorm/insts.c:1766:21: warning: suggest braces around initialization of subobject [-Wmissing-braces]
            /*II_V_0F_AE_02*/{ 0x1d1, 9963, 0x40, 0, 0, 0, 0 },
                               ^~~~~~~~~~~
                               {          }
    ../../../share/xdetour/distorm/insts.c:1767:21: warning: suggest braces around initialization of subobject [-Wmissing-braces]
            /*II_V_0F_AE_03*/{ 0x1d1, 9992, 0x40, 0, 0, 0, 0 }
                               ^~~~~~~~~~~
                               {          }
    381 warnings generated.

Please fix these warnings. Thanks.

**Comment by AaronNGray** [comment]
write a patch !

**Comment by gdabah** [comment]
So sub-structures should be enclosed with an extra pair of parentheses...
Will add that.
