### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by gusrl1005** [gdabah/distorm#117]
./configure
............................
.............................
.............................
make
..................
..................
...................
make[2]: aarch64-arm-darwin-ar : No such file or directory
make[2]: *** [libiberty.a] Error 1
make[1]: *** [all-libiberty] Error 2
make: *** [all] Error 2

Is this a problem with the toolchain?

**Comment by gdabah** [comment]
Got it working? Sorry for late reply.

**Comment by gusrl1005** [comment]
The only reason I do it is because of gdb. Is it possible to get gdb in 64bit environment? If not, let me know how to do it.
