### ISSUE TITLE
Hex Opcode from Binary

### ISSUE THREAD

**Issue by fred26** [gdabah/distorm#122]
Is there a way to retrieve the hex opcode for any binary code?

Let's say 44 0F45 C8 is decoded to cmovne r9d,eax, but need the 0F45 for cmovne mnemonic

http://ref.x86asm.net/coder64.html

Thanks

**Comment by gdabah** [comment]
Hi
Is it still relevant?

**Comment by fred26** [comment]
No, it isn’t.
Thanks
