### ISSUE TITLE
Failed optimization on BigEndian architectures

### ISSUE THREAD

**Issue by mcepl** [gdabah/distorm#123]
BigEndiand architectures don't work well with some optimizations so we had to switch them off. This probably should be ``#ifdefed`` just for particular architectures:

```diff
--- a/src/config.h
+++ b/src/config.h
@@ -57,7 +57,7 @@ This library is licensed under the BSD l
 
 #define _DLLEXPORT_
 #define _FASTCALL_
-#define _INLINE_ static
+#define _INLINE_
 /* GCC ignores this directive... */
 /*#define _FASTCALL_ __attribute__((__fastcall__))*/
 
--- a/src/prefix.c
+++ b/src/prefix.c
@@ -116,7 +116,7 @@ uint16_t prefixes_set_unused_mask(_Prefi
  * Mark a prefix as unused, and bookkeep where we last saw this same type,
  * because in the future we might want to disable it too.
  */
-_INLINE_ void prefixes_track_unused(_PrefixState* ps, int index, _PrefixIndexer pi)
+static void prefixes_track_unused(_PrefixState* ps, int index, _PrefixIndexer pi)
 {
        prefixes_ignore(ps, pi);
        /* Book-keep the current index for this type. */
```

**Comment by gdabah** [comment]
@mcepl Hi, thanks for this info. What arch did you use if you can say? I find this compiler issue very strange. I can't see how it is related with big endian.

**Comment by mcepl** [comment]
I have certainly the problem on PPC64 ([build log](https://github.com/gdabah/distorm/files/2520955/ppc64_python-distorm3_log.txt)).

**Comment by gdabah** [comment]
@mcepl can you please ping me at distorm@gmail.com and I will send you 2 files to retry this?

**Comment by gdabah** [comment]
ok I get it, the compiler doesn't like to see "static static" as a prefix for the functions obviously... :)
