### ISSUE TITLE
Problems decoding instructions once at a time

### ISSUE THREAD

**Issue by computerhost1** [gdabah/distorm#129]
I am writing a debugger in ubuntu (amd64) and i use `distorm_decode` to display each instruction in single-step mode. However, `distorm_decode` doesn't decode `bndmov` instruction. **To make it more strange, the return code is `DECRES_MEMORYERR` and `usedInstructionsCount` becomes zero.**

I actually want the decoder to show `DB 0x66` at least.

Here is the instruction (the output of disasm example program)

```
diStorm version: 3.4.0
bits: 64
filename: /tmp/mmap.raw
origin: 00007fe5031768f2
00007fe5031768f2 (01) 66                       DB 0x66  <-- this instruction should be bndmov [rsp+0x100],bnd0
00007fe5031768f3 (01) 0f                       DB 0xf
00007fe5031768f4 (07) 1b842400010000           SBB EAX, [RSP+0x100]
00007fe5031768fb (01) 66                       DB 0x66  <-- this instruction should be bndmov [rsp+0x110],bnd1
00007fe5031768fc (01) 0f                       DB 0xf
00007fe5031768fd (07) 1b8c2410010000           SBB ECX, [RSP+0x110]
...
```

And my program's output (part):

```
...
[STAT] Inferior 9311: 00007fe5031768e0 c5fd7fb424c0000000       VMOVDQA [RSP+0xc0], YMM6
[STAT] Inferior 9311: 00007fe5031768e9 c5fd7fbc24e0000000       VMOVDQA [RSP+0xe0], YMM7
[STAT] Inferior 9311: @0x7fe5031768f2 <diStrom decoded 0 instruction!>
[STAT] Inferior 9311: @0x7fe5031768fb <diStrom decoded 0 instruction!>
[STAT] Inferior 9311: @0x7fe503176904 <diStrom decoded 0 instruction!>
[STAT] Inferior 9311: @0x7fe50317690d <diStrom decoded 0 instruction!>
[STAT] Inferior 9311: 00007fe503176916 488b7310                 MOV RSI, [RBX+0x10]
...
```

What's the problem? Or what is the best practice for my requirement?

**Comment by gdabah** [comment]
The MPX instruction set isn't supported in diStorm.
Perhaps I will add it in the future.

**Comment by computerhost1** [comment]
Well, my real problem is, i am forced to print out something like "unidentified instruction" when i get `DECRES_MEMORYERR`. That doesn't really make sense, right?

**Comment by gdabah** [comment]
What happens perhaps is that you pass only one result output at a time, and since the undefined byte/instruction counts as an instruction, it will proceed to the next instruction, and then it will see that it cannot write the output since it has reached the maximum capacity and return memory-err.
