### ISSUE TITLE
How to build to python3?

### ISSUE THREAD

**Issue by eribertomota** [gdabah/distorm#130]
Hi Gil,

The program appears be able to provide Python 3 bindings but do not make it.

Please, add a rule in setup.py to provide Python 2/3 bindings when possible.

Cheers,

Eriberto

**Comment by gdabah** [comment]
@eribertomota Hi again :)
I'm not really sure what you mean. How do you install?

**Comment by eribertomota** [comment]
Hi Gil,

I think that I did a big mistake. However, I suggest update README to say that distorm3 is Python2/3 compatible and how to build via Python3.

Cheers,

Eriberto

**Comment by gdabah** [comment]
Current readme says: "Installing diStorm3 - Clone repo locally and then 'python setup.py install' or alternatively: 'python -m pip install distorm3'."

**Comment by eribertomota** [comment]
Em qua, 5 de dez de 2018 às 14:21, Gil Dabah <notifications@github.com>
escreveu:

> Current readme says: "Installing diStorm3 - Clone repo locally and then
> 'python setup.py install' or alternatively: 'python -m pip install
> distorm3'."
>

Not 'python3 setup.py install' for Python 3 bindings?

Cheers,

Eriberto

**Comment by gdabah** [comment]
Yep, that's the same. If someone cannot go past that phase, then it's a pity :)
