### ISSUE TITLE
Relative Jump and Operands

### ISSUE THREAD

**Issue by Nifury** [gdabah/distorm#138]
When decoding relative jump/call instructions, e.g., `751D jnz xxx`, the value of the operand is `1F` instead of `1D`. 

I was expecting `jump target = address + op.value + instruction.len`. 

![capture](https://user-images.githubusercontent.com/7867461/61570800-e13e5480-aa43-11e9-9198-6e6b7f267c75.PNG)

**Comment by gdabah** [comment]
There’s a type and a value.
See documentation.

**Comment by Nifury** [comment]
Okay I just found it returns absolute address.
[https://github.com/gdabah/distorm/blob/master/python/distorm3/\_\_init\_\_.py#L841](url)
