### ISSUE TITLE
I created windows installation for version 3.4.1 Python36 64bit 

### ISSUE THREAD

**Issue by aspir** [gdabah/distorm#139]
Hey I created a windows installation for distorm3.4.1 for Python36-64bit, and a wheel installation
Can one of the administrators here upload it to PYPI?
[windows_distorm3.zip](https://github.com/gdabah/distorm/files/3515057/windows_distorm3.zip)

**Comment by gdabah** [comment]
Hey @aspir 
Sorry, I missed this issue. I will upload a new one compiled on my own, thanks.
