### ISSUE TITLE
decoder.h header still has GPL license

### ISSUE THREAD

**Issue by scampbird** [gdabah/distorm#141]
Hi - I know it's a minor thing, but decoder.h still claims it is licensed under GPL v3, whereas all other code says BSD. I assume that's just an oversight?

Thanks.

**Comment by gdabah** [comment]
Good catch, thanks!

**Comment by gdabah** [comment]
Fixed. I wonder if you used Blackduck or something ? :)

**Comment by scampbird** [comment]
Thanks - and nope, just spotted it in passing!
