### ISSUE TITLE
PyOxidizer support

### ISSUE THREAD

**Issue by jayvdb** [gdabah/distorm#142]
PyOxidizer breaks on distorm as 

1. it doesnt provide `__file__`   See indygreg/PyOxidizer#69 for more info about why, but the tl;dr version is `__file__` is an optional attribute and should not be relied upon.
2. it builds libs statically, so the external lib search is unnecessary. it is compiled in.  It can be detected using `sys.oxidized`

**Comment by gdabah** [comment]
Hi @jayvdb
So what are you suggesting the code should do, as it looks for the .so/.dll to load?

**Comment by jayvdb** [comment]
Hi @gdabah , the only approach that I know will work for the second problem I mentioned is having a cython or cffi shim that exposes the library functions that are needed.

However, it would still be useful if distorm solved the first problem I mentioned, the use of `__file__`, as there are ways to hack PyOxidizer so that it can access shared libraries outside of the static binary, which works around the second problem.  At the moment, the `__file__` problem means that distorm fails during `import` with a `NameError`, which is really difficult to workaround (I am working around it by injecting a fake `__file__` value into the stub which loads distorm, but that hack is horrid).

Having an optional envvar for locating the libs might be a suitable fallback if `__file__` is missing?

**Comment by gdabah** [comment]
I am willing to change it to whatever. What I don’t understand is what the
fallback should be. Cause eventually I have to load the dynamic library.

**Comment by jayvdb** [comment]
Could distorm load the dynamic libraries from a path specified in an environment variable?
e.g. `DISTORM_LIBS` ?

**Comment by gdabah** [comment]
Yep, but I rather use a generic envar.

**Comment by gdabah** [comment]
@jayvdb  Where are we standing on this? I want to make the change. if __FILE__ isn't there, what's a good way to fetch the self-file-path?

**Comment by jayvdb** [comment]
ZipApps, PyOxidizer, Nuitka standalone, etc all have only one file residing on a filesystem: `sys.executable`.  Everything else is either converted into object code, or is embedded inside `sys.executable`.

Loading extra libs from the same path as `sys.executable` would be a quite sensible approach.

**Comment by gdabah** [comment]
I will take a look at that. Thanks for the very quick response.

**Comment by gdabah** [comment]
@jayvdb I pushed something so if it detects oxidizer it won't set any path and just try to load the library without any prefixed directory. Can you please run it to test?

**Comment by gdabah** [comment]
@jayvdb Perhaps it's now fixed with latest setup.py.
