### ISSUE TITLE
Add support for DF_STOP_ON_HLT?

### ISSUE THREAD

**Issue by Maimonator** [gdabah/distorm#143]
Hi!
I've been using distorm's C library with `DF_STOP_ON_RET` and it seems as if many ELF Files that have been compiled with libc has their entry functions look something like this:
![image](https://user-images.githubusercontent.com/8999543/71180857-b7e85580-227b-11ea-8547-e301afd1133d.png)

As you can see the function ends with the `HLT` instruction and not `RET`.
Since i'm trying to disassemble functions the ideal solution would be if I could send `DF_STOP_ON_HLT | DF_STOP_ON_RET` as a parameter.
Frankly, the code is quite complicated and for now I've added `HLT` to the function `UpdateForFlowControl` to receive the flag `FC_RET` but this doesn't seem like the optimal solution.

Was hoping for your cooperation in helping me with this issue.
Thanks a lot, and much much respect on this awesome library.

**Comment by gdabah** [comment]
Hi Tal

Basically it is required to add a flag/mask to the stop commands. And then
add a check in the code.

Did you try to touch the code or added an artificial condition outside the
library?

**Comment by Maimonator** [comment]
Adding an artificial condition will break the easy usage of `distorm_decompose`, cause that would mean I would have to parse one instruction at a time even though the documentation states that the minimal size of `maxInstructions` should be 15.
I can add another flag to the stop commands, but because `META_GET_FC ` does `((meta) & 0x7)` I figured that adding another bit might be more tricky then I think so I wanted your thoughts on that.
Anyways if this is also your suggested solution, I don't mind opening a PR and adding that.

Thanks a lot!

**Comment by gdabah** [comment]
Yes, we're out of bits for the meta byte. Damn.
In your snippet above, the CRT's main won't get back to execute the HLT instruction, right? So it's just there as a hint for disassembler or something like that.

**Comment by Maimonator** [comment]
I'm actually not sure about this specific code example since I've never ran it.
But a quick google search brought this up:
https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/x86_64/start.S;hb=HEAD
notice the comment on line 122
`/* Crash if somehow `exit' does return.  */`
So I guess the disassembler takes it as a hint.

**Comment by gdabah** [comment]
Hmm it's a privileged instruction, that's why it would crash.
Not sure if I should fold it in the INT family. I'm afraid it will break compatibility.

**Comment by Maimonator** [comment]
What about increasing the size of the meta byte?
Or maybe adding a different struct member?
Current flags could keep their original bits, so backwards compatibility still exists 
The only thing that would change is the size of `_DInst` so whoever updates will need to update the `.h` files he uses too, which seems fairly reasonable in my opinion.
Another solution could be guaranteeing the decomposition of one instruction at a time and let whoever receives the instruction deal with it themselves.

**Comment by gdabah** [comment]
If it’s part of how the compiler works it has to be integrated inside
distorm. I will check out the structure layout and see if the alignment can
work out the enlargement of that field.

**Comment by Maimonator** [comment]
Okay cool, lots of thanks!
Let me know if I can help

**Comment by gdabah** [comment]
Okay, the good news is that I can add the extra byte to Meta to make it a short. And then it fits in. I will do it next week.

**Comment by Maimonator** [comment]
Cool!
I would actually love to do it myself if you wouldn't mind :)

**Comment by gdabah** [comment]
There are many changes that need to be done. Like updating the py and java
files and actually I wanted to use the opportunity to reposition some
fields. But you’re welcome to start and I will go over it.

**Comment by gdabah** [comment]
I will work on what you sent on Sunday. Thanks for the patience :)

**Comment by Maimonator** [comment]
Thanks a lot, I had fun :)

**Comment by gdabah** [comment]
Impressive work BTW!
