### ISSUE TITLE
DISTORM_DECRES_FILTERED 

### ISSUE THREAD

**Issue by Antiever** [gdabah/distorm#156]
`DISTORM_DECRES_FILTERED` what is it for?
Can't find any info in wiki or source code...

Btw it would be nice to have a more organized docs if it's possible :)

**Comment by gdabah** [comment]
It means the result was filtered because there was user input of how to
decode.
Like explained here:
https://github.com/gdabah/distorm/wiki/diStormFeatures


But you’re right it should be more explicit.
Also, more organized how?
Thanks

**Comment by Antiever** [comment]
Thx! 

> Also, more organized how?

When in sources you see a line like
`See more documentation online at the GitHub project's wiki`
you expect that there is a "super full" version of the documentation :)

But in fact, you have to jump back and forth collecting everything piece by piece from the mentions in the wiki notes and sources

And as "entities should not be multiplied without necessity" one more thing - is string formatting really hard-coded?
like `MOV RCX, [RSP+0xb8]`
and if I want to see it like `mov rcx, [rsp+0xB8]` I need to manually convert (LCase all + UCase numbers) after format, right?

**Comment by gdabah** [comment]
Not sure what you mean you’re saying it’s not full. I thought it’s pretty
elaborate. I am covering all features (still can get better I guess). But I
never got feedback so it’s hard to know if it’s good or not.

Yes, you will have to upcase yourself.

**Comment by Antiever** [comment]
> Yes, you will have to upcase yourself

There is some kind of "unspoken standard" - addresses in UCase other in LCase:

![dis](https://user-images.githubusercontent.com/9666515/106524259-5fadfa80-64f3-11eb-90ba-a8939631697e.png)
etc 

Almost every "research" tool looks like that.
May I ask you why distorm output hard-coded so unusual way? :)

Can I hope for a couple of lines that need to be replaced in the source code to avoid performance loss (what happens with double formatting)?

**Comment by gdabah** [comment]
You need it dynamically?

For static -
You can low case all registers in the table and all mnemonics and you’re
good.
And perhaps a few string literals. But that’s it.


I started this project 18 years ago. Can’t tell you why I chose upcase. I
thought it made more sense but it doesn’t mean much anyway.

**Comment by Antiever** [comment]
> You can low case all registers in the table

I apologize, I was too lazy to study the source code in detail. Shame on me :)
And what about addresses: `0xb8` > `0xB8` ?

**Comment by gdabah** [comment]
No worries. All numbers are generated in one file and requires tiny changes.
https://github.com/gdabah/distorm/blob/master/src/textdefs.c

TextBTable
And nibble to char.

**Comment by gdabah** [comment]
@Antiever DISTORM_DECRES_FILTERED is a long dead hack, removed from source code.
Thanks
