### ISSUE TITLE
[request] eschew [CR4:....] in favor of QWORD/etc

### ISSUE THREAD

**Issue by sfinktah** [gdabah/distorm#159]
One of the wonderful things about distorm3, is that its output is perfectly compatible with `nasm` (`yasm`).

That is, until we hit an SIMD instruction like

    F2 0F 10 4C 18 60                       movsd   xmm1, qword ptr [rax+rbx+60h]
    F2 0F 11 8C 0A 70 01 00+                movsd   qword ptr [rdx+rcx+170h], xmm1

Which is resolved as

    MOVSD XMM1, [CR4:RAX+RBX+0x60]
    MOVSD [CR4:RDX+RCX+0x170], XMM1

I just found this example too:

    48 83 24 1E 00                          and     qword ptr [rsi+rbx], 0

Resolves to:

    AND QWORD [CR4:RSI+RBX], 0x0

I've written a little python shim to fix it for my own purposes, but it just seems a shame.

I should note that both the example instructions will compile in nasm/yasm if the CR4 is simply removed, but this may not be the case for all such instructions -- I have had a previous issue (with another disassembler) where the size was required to assemble.

**Comment by gdabah** [comment]
@sfinktah You revealed yet another weird bug after the huge change I did in April. Thanks!! I'm working on a fix.
