### ISSUE TITLE
F3 48 0F 2A 04 F8  - Missing PTR SIZE: "CVTSI2SS XMM0, [RAX+RDI*8]"

### ISSUE THREAD

**Issue by sfinktah** [gdabah/distorm#165]
Should decompile as 

    CVTSI2SS XMM0, QWORD [RAX+RDI*8]

as the instruction is valid as `DWORD` or `QWORD` and won't assemble without the size being specified.

**Comment by sfinktah** [comment]
```
F3 48 0F 2A 04 F8 - CVTSI2SS XMM0, QWORD [RAX+RDI*8]
F3 0F 2A 04 F8 - CVTSI2SS XMM0, DWORD [RAX+RDI*8]
```

There is no DQWORD version, so it's safe to say that if the source (right) operand is not a register, then it it is always going to need an explicit size specifier, regardless of whether it is the SSE, AVX or AVX512 version.

https://www.felixcloutier.com/x86/cvtsi2ss

**Comment by gdabah** [comment]
Nice catch, it was an exceptional instruction that needed a special treatment inside distorm_format_size.
Thanks!
