### ISSUE TITLE
i dont understand why looping on this based on the demo .. showing garbage text

### ISSUE THREAD

**Issue by gurachan** [gdabah/distorm#172]
![image](https://user-images.githubusercontent.com/12135498/121960837-36eb1b00-cd99-11eb-89a2-a5fe1e788494.png)

even tho i put pass its still outputting that.. u cant log the variables also..

**Comment by gdabah** [comment]
Here's an example of how I use it in tests.
https://github.com/gdabah/distorm/blob/master/python/test_distorm3.py#L66
Note sure why it prints something at all if you don't invoke 'print' yourself.
That's weird.
