### ISSUE TITLE
Wiki doesn't load

### ISSUE THREAD

**Issue by douggard** [gdabah/distorm#88]
Whenever I click a wiki or documentation link on the page, or click wiki on the side of the project, it just redirects me to the Github repository. Thanks!

**Comment by fabaff** [comment]
Works for me....https://github.com/gdabah/distorm/wiki

**Comment by hyskyder** [comment]
I experience the same problem in Chromn48 on Win7.

**Comment by gdabah** [comment]
Fixing it now, thanks.
