### ISSUE TITLE
FMA4 Instructions not supported

### ISSUE THREAD

**Issue by G-ram** [gdabah/distorm#93]
I was trying to disassemble libm.so on x86_64, and distorm fails on the following instruction (treating it as a series of DBs):

`0x00000000404ac413 <__cos_fma4+2627>:        c4 e3 f1 6b c4 00       vfmaddsd %xmm4,%xmm0,%xmm1,%xmm0`

vfmaddsd is an FMA4 instruction (AMD specific). Is there any support for FMA instructions in distorm/is there any support planned?

**Comment by gdabah** [comment]
Hi
Currently it's not planned, maybe in the future.
