### ISSUE TITLE
problem decoding x64 instruction "mov rax, 0"

### ISSUE THREAD

**Issue by Pantman** [gdabah/distorm#94]
I've come across a problem decoding the following byte sequence:

48 C7 C0 00 00 00 00

The instruction should decode to "mov rax, 0". If I use onlinedisassembler.com I see the expected output, but distorm produces the following output:

diStorm version: 3.3.0
0000000000000000 (01) 48                       DB 0x48
0000000000000001 (01) c7                       DB 0xc7
0000000000000002 (03) c00000                   ROL BYTE [RAX], 0x0
0000000000000005 (02) 0000                     ADD [RAX], AL

The code I used is based on the distorm disasm sample code, but with file handling removed, and replaced with a fixed buffer containing the byte code.

The parameters to distorm_decode are:

_OffsetType codeOffset = 0
const unsigned char* code = pointer to array containing {0x48, 0xC7, 0xC0, 0x00, 0x00, 0x00, 0x00}
int codeLen = 7
_DecodeType dt = Decode64Bits

**Comment by Pantman** [comment]
Has anyone else come across this issue when decoding x64 instructions?

**Comment by gdabah** [comment]
Thanks, just fixed it. Updating soon.
