### ISSUE TITLE
The pypi version seems incorrect

### ISSUE THREAD

**Issue by utkonos** [gdabah/distorm#97]
The version in pypi is 3.3.1, but the latest release here at github is 3.3.0. This seems to be confusing pip. The pip list --outdated command returns the following:
distorm3 (3.3.0) - Latest: 3.3.1 [sdist]

However, when I do a pip install -U distorm3 it does the following:
Collecting distorm3
Installing collected packages: distorm3
  Found existing installation: distorm3 3.3.0
    Uninstalling distorm3-3.3.0:
      Successfully uninstalled distorm3-3.3.0
Successfully installed distorm3-3.3.0

And pip list --outdated again shows a new version available. It looks to be related the pypi package:
distorm3-3.3.1.zip (md5), but the version is showing as 3.3.0:
Package Index > distorm3 > 3.3.0

**Comment by gdabah** [comment]
Working on a fix, thanks.
