### ISSUE TITLE
Wrong decoding MOV (0xC7) instruction

### ISSUE THREAD

**Issue by AlexanderBagel** [gdabah/distorm#98]
Sample:
DB 0xC7, 0xC1, 0x08, 0x00, 0x00, 0x00

must be disassembled as: "MOV ECX, 8"

but output:
C7                                         DB 0xC7 
C1 08 00                                   ROR DWORD [EAX], 0x0
00 00                                      ADD [EAX], AL

**Comment by AlexanderBagel** [comment]
UPD: This behavior occurs when using the release version of the library

**Comment by gdabah** [comment]
Yep, just validated, I broke this instruction. Working on a fix. Thanks!
